[package]
name = "aiq"
version = "0.1.0-alpha.6"
edition = "2024"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/wyfo/aiq"
keywords = [
  "atomic",
  "lock-free",
  "no-std",
  "async",
]
categories = [
  "concurrency",
  "data-structures",
  "no-std",
]
repository = "https://github.com/wyfo/aiq"
description = "An intrusive list with lock-free insertion."
rust-version = "1.95"

[features]
default = ["std"]
atomic-wait = ["dep:atomic-wait"]
lock_api = ["dep:lock_api"]
parking_lot = ["dep:parking_lot", "dep:parking_lot_core", "lock_api"]
portable-atomic = ["dep:portable-atomic"]
pthread = ["dep:libc"]
std = []

[dependencies]
atomic-wait = { version = "1", optional = true }
cfg-if = "1"
lock_api = { version = "0.4", optional = true }
parking_lot = { version = "0.12", optional = true }
parking_lot_core = { version = "0.9", optional = true }
portable-atomic = { version = "1", optional = true, default-features = false, features = ["require-cas"] }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", optional = true }

[dev-dependencies]
criterion = "0.8.2"
futures = "0.3.32"
rstest = "0.26.1"
tokio = { version = "1.49.0", features = ["full"] }
tokio-test = "0.4.5"

[target.'cfg(loom)'.dependencies]
loom = "0.7.2"
const_fn = "0.4.12"

[target.'cfg(loom)'.dev-dependencies]
loom = { version = "0.7.2", features = ["futures"] }

[lib]
test = false

[[bench]]
name = "notify"
harness = false

[[bench]]
name = "notify_lazy_linked"
harness = false

[[bench]]
name = "tokio_notify"
harness = false

[[bench]]
name = "semaphore"
harness = false

[[bench]]
name = "semaphore_lazy_linked"
harness = false

[[bench]]
name = "tokio_semaphore"
harness = false

[package.metadata.docs.rs]
all-features = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  "cfg(nightly)",
  "cfg(loom)",
  "cfg(aiq_notify_fetch_max)",
] }
unsafe_op_in_unsafe_fn = "warn"

[lints.clippy]
dbg_macro = "warn"
semicolon_if_nothing_returned = "warn"