[package]
name = "maillon"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/wyfo/maillon"
keywords = [
    "atomic",
    "lock-free",
    "no-std",
    "async",
]
categories = [
    "concurrency",
    "data-structures",
    "no-std",
]
repository = "https://github.com/wyfo/maillon"
description = "A concurrent intrusive list with lock-free insertion, mainly for building synchronization primitives."
rust-version = "1.70"

[features]
default = ["std"]
lock_api = ["dep:lock_api"]
parking_lot = ["dep:parking_lot", "dep:parking_lot_core", "lock_api"]
portable-atomic = ["dep:portable-atomic"]
pthread = ["dep:libc"]
std = ["atomic-backoff/std"]

[dependencies]
atomic-backoff = { version = "0.1.1", default-features = false }
cfg-if = "1"
lock_api = { version = "0.4", optional = true }
parking_lot = { version = "0.12", optional = true }
parking_lot_core = { version = "0.9", optional = true }
portable-atomic = { version = "1", optional = true, default-features = false, features = ["require-cas"] }

[target.'cfg(any(target_os = "linux", target_os = "android", target_os = "freebsd", target_os = "macos", target_os = "ios", target_os = "watchos", windows))'.dependencies]
atomic-wait = "1"

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", optional = true }

[dev-dependencies]
futures = "0.3.32"
rstest = "0.27.0"
tokio = { version = "1.49.0", features = ["full"] }
tokio-test = "0.4.5"

[target.'cfg(not(loom))'.dev-dependencies]
async-event = "0.2"
async-channel = "2.5.0"
asyncband = { version = "0.7", features = ["event", "semaphore"] }
concurrent-queue = "2.5"
criterion = "0.8.2"
divan = "0.1.21"
event-listener = "5.4"
futures-intrusive = "0.5"

[target.'cfg(loom)'.dependencies]
loom = "0.7.2"
const_fn = "0.4.12"

[target.'cfg(loom)'.dev-dependencies]
loom = { version = "0.7.2", features = ["futures"] }

[[bench]]
name = "asyncband"
harness = false

[[bench]]
name = "async_channel"
harness = false

[[bench]]
name = "futures_intrusive"
harness = false

[[bench]]
name = "notify"
harness = false

[[bench]]
name = "notify_lazy_linked"
harness = false

[[bench]]
name = "tokio_notify"
harness = false

[[bench]]
name = "semaphore"
harness = false

[[bench]]
name = "semaphore_lazy_linked"
harness = false

[[bench]]
name = "tokio_semaphore"
harness = false

[package.metadata.docs.rs]
all-features = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    "cfg(nightly)",
    "cfg(loom)",
    "cfg(maillon_notify_fetch_max)",
] }
unsafe_op_in_unsafe_fn = "warn"

[lints.clippy]
dbg_macro = "warn"
semicolon_if_nothing_returned = "warn"
